kujaku11/mth5

- examples/make_mth5_from_nims.py
- examples/make_mth5_from_xml.py
- examples/make_mth5_from_z3d.py
- examples/make_stationxml_from_mt.py
- examples/test_examples.py
- mth5/utils/pathing.py
added a test_examples.py to the examples/ folder so we can now run all the examples en masse with pyttest.
> merged examples under a single test_examples.py for use with pytest

- mth5/io/zen.py
Fixed numpy warning messages about deprecated methods fromstring and tostring.
> Fix np warnings

- mth5/clients/make_mth5.py
- mth5/groups/filter_groups/zpk_filter_group.py
- mth5/groups/master_station_run_channel.py
- mth5/groups/survey.py
- mth5/helpers.py
- mth5/mth5.py
- tests/timeseries/test_channel_ts.py
- tests/version_1/test_filters.py
- tests/version_1/test_from_stationxml.py
- tests/version_2/test_build_from_experiment.py
- tests/version_2/test_filters.py
- tests/version_2/test_from_stationxml.py
- tests/version_2/test_make_mth5.py
> updated dtype in zpk to complex

- .bumpversion.cfg
- HISTORY.rst
- README.md
- docs/README.rst
- mth5/__init__.py
- setup.py
Bump version with updating docs.
> Bump 0.3.1 -> 0.4.0

- mth5/groups/run.py
see notes in issue [#175](https://github.com/kujaku11/mth5/issues/175)
> Add try except for runs with no channels

- mth5/mth5.py
- tests/test_mth5_basics.py
Ugh, this should have referenced issue #182 _not 184_ :/
> Add return self to open_mth5()

- mth5/utils/fc_tools.py
This adds the functionality referenced in issue #209.
It should also have
> Fix issue 209

- mth5/utils/fc_tools.py
- tests/utils/test_fc_tools.py
- tests/version_1/test_fcs.py
Fix issue 209a
- create a class `MultivariateDataset` class to wrap the multivariate xarrays
- `MultivariateLabelScheme` class to manage how we label multivariate channels
-
> Add some more multivariate functionality

- mth5/utils/fc_tools.py
- tests/version_1/test_fcs.py
- added a try/except
- if exception encountered, message telling user what FCs are there, and suggesting to add the requested group
- added a test for the exception
> Minor multivariate updates

- mth5/__init__.py
- mth5/mth5.py
- mth5/tables/__init__.py
- mth5/tables/fc_table.py
- tests/version_1/test_fcs.py
- tests/version_1/test_mth5.py
- tests/version_2/test_mth5.py
Add and FCSummary to mth5.
This is a prototype.
> Fix issue 233

- mth5/data/make_mth5_from_asc.py
A synthetic e-field flip correction was recently added This reversed the polarity of the  'ex', 'ey' columns of dataframe right after it gets read-in.  However, the dataframe column names come from the channel nomenclature, and these can be, for example 'e1', 'e2'.
Some notes about a permanent fix are in Issue 236
> hotfix synthetic electric field polarity (#236)

- .bumpversion.cfg
- HISTORY.rst
- README.md
- code.json
- docs/README.rst
- mth5/__init__.py
- setup.py
> Bump version: 0.4.5 → 0.4.6

- mth5/data/paths.py
- mth5/data/station_config.py
This all tasks in issue #191  are complete.
@kujaku11 as a final thing, I also added a completely built, 6MB mth5 file (`test12rr.py`), but named it `synthetic_test_data.h5`.  This is to make using the synthetic data easier when writing tests in aurora.
> Fix issue 191

- .bumpversion.cfg
- .github/workflows/tests.yml
- HISTORY.rst
- README.md
- code.json
- docs/README.rst
- mth5/__init__.py
- setup.py
> Bump version: 0.4.6 → 0.4.7

- mth5/timeseries/channel_ts.py
Replaced the use of np.median with scipy.stats.mode in the sample rate computation in the high frequency case, in ChannelTS.compute_sample_rate
> Fix Issue 241

- mth5/timeseries/run_ts.py
This fixes the calibration issue in [earthscope-mt_course issue 10](https://github.com/simpeg-research/earthscope-mt-course/issues/10)
> Fix issue 252

- .bumpversion.cfg
- HISTORY.rst
- README.md
- code.json
- docs/README.rst
- mth5/__init__.py
- mth5/timeseries/run_ts.py
- setup.py
> Bump version: 0.4.8 → 0.4.9

- mth5/groups/fc_dataset.py
- mth5/timeseries/ts_helpers.py
- tests/timeseries/test_ts_helpers.py
> FC dataset end time consistency

- .bumpversion.cfg
- HISTORY.rst
- README.md
- code.json
- docs/README.rst
- mth5/__init__.py
- setup.py
Bump version and update `History.md` for new release.
> Bump version 0.4.9 --> 0.4.10

- .github/workflows/tests.yml
- mth5/timeseries/scipy_filters.py
- mth5/timeseries/spectre/helpers.py
- mth5/timeseries/spectre/prewhitening.py
- tests/timeseries/spectre/test_spectrogram.py
- start moving tools from aurora stft tests to mth5
> Continue 271 after changes in mt_metadata

- mth5/timeseries/channel_ts.py
Housekeeping:
- remove unused scipy import (and alphabetize)
> latest updates

- mth5/timeseries/run_ts.py
replacing use of median to mode in _compute_sample_rate from RunTS
> Fix issue 279
